version: '3.1'
services:
  db:
    container_name: docker_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    # volumes:
    #   - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql